# Generated by Django 4.0.5 on 2022-06-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('saddress', models.CharField(max_length=50)),
                ('smobile', models.CharField(max_length=50)),
            ],
        ),
    ]
